### PR TITLE
Update README.md: adds pdfium-vfp to related projects

### PR DESCRIPTION
**Pull request by dmitriychunikhin**

### CODE REVIEW

**Comment by mara004** [comment]
Interesting, but I've read that Visual FoxPro has been decommissioned and abandoned by Microsoft about 10 years ago.
And it sounds like VPFX is not an open-source re-implementation of the VPF core, but rather a set of packages written in VFP, right? In that case, why are new projects being created for an unmaintained, proprietary programming language?

I have no objection to mentioning pdfium-vfp, just wondering about that situation and whether I understood correctly?

**Comment by dmitriychunikhin** [comment]
Well, the short answer is VFPA
http://www.baiyujia.com/vfpadvanced/
It' exists since 2012, has x64 version and somehow evolving http://www.baiyujia.com/vfpadvanced/f_vfpa_history.asp

So, vfp is not completly abandoned, not thriving yep.

Other interesting efforts:

foxlite https://github.com/Irwin1985/FoxLite

xsharp https://github.com/X-Sharp/XSharpPublic

**Comment by bblanchon** [comment]
Merged in 21cce31.
Thanks!

**Comment by dmitriychunikhin** [comment]
Thank you!

**Comment by mara004** [comment]
Thanks for the pointers.
I'm curious how VFPA works? How can it fix bugs in VFP if the core was not open-sourced (or so I read) ? Has it acquired the code from Microsoft? Or is it an independent re-implementation?

**Comment by dmitriychunikhin** [comment]
They patch original MS binaries.

**Pull request closed without merging**
